### PR TITLE
1.0.0 :tada:

### LINKED ISSUE #14: Issue with logout
I think I've spotted some issue with logging out from services:

Here is a network call snapshot from my web browser:

```
logout
/api/1.0/dropbox
Status Code:200 OK
{"success":true,"message":"Now logged out."}


logout
/api/1.0/www
Status Code:200 OK
{"success":true,"message":"Now logged out."}


ls/
/api/1.0/www/exec
Status Code:401 Unauthorized
{
  "success": false,
  "message": "User not connected yet. You need to call the 'login' service first.",
  "code": 401
}


list
/api/1.0/services
Status Code:200 OK
[{"name":"dropbox","display_name":"Dropbox","image_small":"unifile-assets/services/dropbox.png","description":"Edit html files from your Dropbox.","visible":true,"isLoggedIn":true,"isConnected":true,"isOAuth":true,"user":{"display_name":"Thomas Fétiveau","quota_info":{"available":2952790016,"used":2402940491}}},{"name":"www","display_name":"Web server","image_small":"unifile-assets/services/www.png","description":"Edit files on the server where Silex is installed.","visible":true,"isLoggedIn":false,"isConnected":false,"isOAuth":false},{"name":"ftp","display_name":"FTP","image_small":"unifile-assets/services/ftp.png","description":"Edit files on a web server.","visible":true,"isLoggedIn":false,"isConnected":false,"isOAuth":false,"user":{"host":"blablablabla","port":"21","username":"blabla","password":"blablabla"}}]


ls/
/api/1.0/dropbox/exec
Status Code:200 OK
[{"name":"anim3d-zabo-nico","bytes":0,"modified":"Wed, 21 May 2014 19:22:33 +0000","is_dir":true},{"name":"apps","bytes":0,"modified":"Tue, 10 Jun 2014 09:04:47 +0000","is_dir":true},{"name":"EuropaApps","bytes":0,"modified":"Mon, 16 Dec 2013 08:19:23 +0000","is_dir":true},{"name":"Launcher","bytes":0,"modified":"Mon, 16 Dec 2013 08:19:23 +0000","is_dir":true},{"name":"Player_v60x","bytes":0,"modified":"Mon, 16 Dec 2013 08:19:23 +0000","is_dir":true},{"name":"pol","bytes":0,"modified":"Fri, 27 Sep 2013 08:25:13 +0000","is_dir":true},{"name":"test1.htm","bytes":22,"modified":"Thu, 17 Apr 2014 18:48:14 +0000","is_dir":false},{"name":"test2.htm","bytes":22,"modified":"Thu, 17 Apr 2014 18:48:30 +0000","is_dir":false},{"name":"test3.htm","bytes":22,"modified":"Sun, 18 May 2014 15:06:35 +0000","is_dir":false},{"name":"test4.htm","bytes":22,"modified":"Sun, 18 May 2014 15:07:05 +0000","is_dir":false}]
```

The problem here is that we expect the call to services/list to return the services with LoggedIn set to false. And it appears to be true for Dropbox... The last ls call should return 401 forbidden. It seems logging out from DB did not succeed whereas it returned true...

Note that the calls after the logout calls (ls, list, ...) happened when logout calls already returned to my browser.

### LINKED ISSUE #33: Multi-tenancy
What is the best way to implement multi-tenancy with this package?

For example, for the `www`, I would like to have `user x`, mapped to `data/x` as the root folder and `user y` mapped to, say `data/y`, as the root www folder.

This should happen upon successful login (automatically), so that `ls /` for user x gives contents of folder `data/x` and for user y gives contents of `data/y`.

Is it possible in the current version?

### LINKED ISSUE #36: Unifile next steps
@KrishnaPG got me thinking about the next version of unifile

Here is what I think we should do
- Refactor the API: no more config but option of the API, and the API which could be used in nodejs or with the command line cli or with HTTP calls as it is today
- Make the HTTP API better: use GET, POST, UPDATE, DELETE... 
- Better doc and a website
- Coding style refactoring: Everything should be cleaned up and ported to ES2015, whith promise, the API should mimic Node.js File System api

And here is the details, feel free to help me on this definition of unifile v1
### Refactor the API

In node, for use with slenium or on the server side when you already have a token (the user has authorized the app)

```
var unifile = require('unifile')
var dropbox = new unifile.Dropbox({
    root : 'dropbox',
    app_key : 'ngk5t8312eo4agh',
    app_secret : '7uxqr625pct7zbl'
})
dropbox.connect(function (authorizeUrl) {
    // open authorizeUrl, login and authorise the app
    // then call this
    dropbox.setSession({
        access_token: 'the access_token from dropbox'
    })
    dropbox.ls('/', function(files) {
        console.log('files and folder at the root of your dropbox:', files);
    });
});
```

Use with CLI

```
$ unifile dropbox ls /
waiting for you to authorize the app (a browser window has opened)
app authorized
file 81 Nov 20 23:22 admin.html
file 302 Nov 20 21:24 login.html
folder 136 Nov 20 23:34 node_modules
```

Use the middleware to activate a service and expose the HTTP route

```
var unifile = require('unifile')
var dropbox = new unifile.Dropbox({
    root : 'dropbox',
    app_key : 'ngk5t8312eo4agh',
    app_secret : '7uxqr625pct7zbl'
})
var router = new unifile.Router(dropbox);
var connect = require('connect')
var app = connect()
app.use('/api/dropbox', router)
```
### Make the HTTP API better

use GET, POST, UPDATE, DELETE... 

See these interesting links
*[Google Cloud Storage API Reference](https://cloud.google.com/storage/docs/json_api/v1/)
### Coding style refactoring

Everything should be cleaned up and ported to ES2015, whith promise, the API should mimic Node.js File System api

See these links for the API methods specs
- https://www.chromestatus.com/feature/5452478162141184
- http://cloud-elements.com/hubs/cloud-storage-documents-hub/

### LINKED ISSUE #57: an issue with github service
I use github service
I saved a website many times and published many times
It made a repo with so many commits github refuses to save
I squashed these commits and now I am able to save again :'(

### LINKED ISSUE #58: remoteStorage protocol consideration
Do you plan the use of an open protocol like RemoteStorage?
https://remotestorage.io/

### LINKED ISSUE #64: npm version
npm is listing 0.0.60 as the latest version, but the git (here) is showing 0.0.59
image

### LINKED ISSUE #66: Batch file handling
Is it possible to remove several files at once? Is it interesting to have such a mechanism?

### LINKED ISSUE #74: WebDAV for 1.0.0
We're very close to the [1.0.0 release](https://github.com/silexlabs/unifile/tree/1.0.0) but for now the only available connectors are:
- FTP
- RemoteStorage
- Dropbox
- GitHub

I'd really love if someone would port the WebDAV (looking at you @Sergio-Muriel :wink:) to the new version so I would have a valuable feedback from this person.

### PR DESCRIPTION
**Pull request by JbIPS**
New official start for Unifile! :tada:

Closes #66, closes #64, closes #58, closes #57, closes #36, closes #14, closes #33, closes #74

### CODE REVIEW

**Comment by JbIPS** [comment]
What's missing before we release this:
- [ ] A `list` function on Unifile
- [ ] Some tests (how?)

**Comment by JbIPS** [comment]
Batch, list and code quality brought by #73

**Comment by JbIPS** [comment]
Ready to merge! But I'll need @lexoyo to take a look 😉

**Comment by JbIPS** [comment]
> This is a great achievement!
Would you do me the honor of merging it? :bowtie:

**Comment by singchan** [comment]
there is only "squash and merge" available to merge... is this on purpose?

**Comment by JbIPS** [comment]
I see "Rebase and merge" too, but I re-enable "Merge commit" if you really prefer.

**Comment by singchan** [comment]
"his branch cannot be rebased due to conflicts"

**Comment by JbIPS** [comment]
With a big reboot like that it's understandable. Just create a merge commit

**Comment by singchan** [comment]
yei!

**Pull request merged**
